# Generated by Django 4.2.9 on 2024-02-08 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='comment_count',
            field=models.IntegerField(default=0, verbose_name='Количество комментариев'),
        ),
        migrations.AddField(
            model_name='news',
            name='favorite_count',
            field=models.IntegerField(default=0, verbose_name='Количество добавивших в избранное'),
        ),
    ]
