# Generated by Django 4.2.9 on 2024-02-08 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_news_comment_count_news_favorite_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='comment_count',
        ),
        migrations.AddField(
            model_name='news',
            name='comments_count',
            field=models.IntegerField(default=0, verbose_name='Количество комментариев'),
        ),
    ]
