# Generated by Django 4.2.9 on 2024-02-20 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_remove_news_comment_count_news_comments_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='comments_count',
            new_name='comment_count',
        ),
    ]
