# Generated by Django 4.2.9 on 2024-02-28 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_rename_comments_count_news_comment_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.TextField(verbose_name='Цвет фона')),
                ('font_size', models.IntegerField(verbose_name='Размер шрифта')),
                ('font_color', models.TextField(verbose_name='Цвет шрифта')),
            ],
        ),
    ]
